namespace Rosalind.Tests

open Xunit
open FsCheck
open Rosalind

module ``Bioinformatics Stronghlod tests`` =
 
    // DNA : Counting DNA Nucleotides
    [<Fact>]
    let ``DNA : Counting DNA Nucleotides``() =
        let result = dna "CCCGCCTTCTCTTCGCTTGAGAGTGCGTCGGTTCGGCGGCATTTACGGAGCCACAGCCACAACCC\
                          ACCCTACATCGTAGGTAGTTTAAGGCCAGTCCCTAATGCGTTCGGGGTAGAGTAAGCGAGTCCCT\
                          TCGAGGACCCAAGCTTTTTTCGATGAAACGCGCTTGTATTCTAGTGCTCGCCCGACTACAAGGAG\
                          CCATCGACGTAGGCCGTTAACAAACCTAGATTCTCAGCTGTTTCGTGGAGGACCGCGCAGAAGCT\
                          CCGGATACGCGTTTCGACACGGTAGCCCCCCCGTCTGTGATAGCAGCGAAGAGATTCTTCACAAC\
                          GGTGCGGACTCGAGGGATTCCCTAGTAAGCCTTCGCCCGATCGGGCTACTTACATTCCCTCGCGC\
                          TACTCTCGTAGGGCCAGGTAGGCCAACGCGTTCCGGTACCCGTTTAGTTCTTGTGGGGATCATGG\
                          GAGAGGTATAGTTGCTCGGGCGGGGTGAGCATCGCAGACTCGTTTTTCACTGCGCTCGCGCATCT\
                          GCCACGAGGACATTCGATCATGTGGCGACGTGATCCCTCTTCAGACCTTATCTTGGAGGGCGCAG\
                          CCGTCCGTTCCACCCGAATGTCCGCGGTTTTGGCGACACTGGTAACCTTAGCAGTCAGTACGCGT\
                          AATAGCGACGGGCCCAAGGCTGCGCGTCCACTCGATTGTAGTGCTTCAGGACCTAGCGCTGCTGA\
                          GATAATGGATACAGTAGGCGAAATCGTGATAGTTGCTATGCCGGCCGTAATCAGAACAAACTAAT\
                          GTCGCCAATACTCCACGGCGCACCTATTGACCACGTTTCTTTCCCCATCCCTTTAAATTCCCGCT\
                          GTCCCGGGCATCGGAATAGGAAGGGACTGAGTACTAGAGAGTCCTGCTGGGTC" = (185, 256, 245, 212)
        Check.Quick result