namespace Rosalind.Tests

open Xunit
open FsCheck
open Rosalind

module ``Bioinformatics Stronghlod tests`` =
 
    // DNA : Counting DNA Nucleotides
    let rawDna = "CCCGCCTTCTCTTCGCTTGAGAGTGCGTCGGTTCGGCGGCATTTACGGAGCCACAGCCACAACCC\
                          ACCCTACATCGTAGGTAGTTTAAGGCCAGTCCCTAATGCGTTCGGGGTAGAGTAAGCGAGTCCCT\
                          TCGAGGACCCAAGCTTTTTTCGATGAAACGCGCTTGTATTCTAGTGCTCGCCCGACTACAAGGAG\
                          CCATCGACGTAGGCCGTTAACAAACCTAGATTCTCAGCTGTTTCGTGGAGGACCGCGCAGAAGCT\
                          CCGGATACGCGTTTCGACACGGTAGCCCCCCCGTCTGTGATAGCAGCGAAGAGATTCTTCACAAC\
                          GGTGCGGACTCGAGGGATTCCCTAGTAAGCCTTCGCCCGATCGGGCTACTTACATTCCCTCGCGC\
                          TACTCTCGTAGGGCCAGGTAGGCCAACGCGTTCCGGTACCCGTTTAGTTCTTGTGGGGATCATGG\
                          GAGAGGTATAGTTGCTCGGGCGGGGTGAGCATCGCAGACTCGTTTTTCACTGCGCTCGCGCATCT\
                          GCCACGAGGACATTCGATCATGTGGCGACGTGATCCCTCTTCAGACCTTATCTTGGAGGGCGCAG\
                          CCGTCCGTTCCACCCGAATGTCCGCGGTTTTGGCGACACTGGTAACCTTAGCAGTCAGTACGCGT\
                          AATAGCGACGGGCCCAAGGCTGCGCGTCCACTCGATTGTAGTGCTTCAGGACCTAGCGCTGCTGA\
                          GATAATGGATACAGTAGGCGAAATCGTGATAGTTGCTATGCCGGCCGTAATCAGAACAAACTAAT\
                          GTCGCCAATACTCCACGGCGCACCTATTGACCACGTTTCTTTCCCCATCCCTTTAAATTCCCGCT\
                          GTCCCGGGCATCGGAATAGGAAGGGACTGAGTACTAGAGAGTCCTGCTGGGTC"
 
    [<Fact>]
    let ``DNA : Counting DNA Nucleotides``() =
        let result = dna rawDna = (185, 256, 245, 212)
        Check.Quick result

    [<Fact>]
    let ``DNA' : Counting DNA Nucleotides``() =
        let result = dna' rawDna = [185; 256; 245; 212]
        Check.Quick result

    [<Fact>]
    let ``DNA'' : Counting DNA Nucleotides``() =
        let result = dna'' rawDna = [('C', 256); ('G', 245); ('T', 212); ('A', 185)]
        Check.Quick result

module ``Bioinformatics Armory tests`` =

    // INI : Introduction to the Bioinformatics Armory
    let rawDna = "CCCGCCTTCTCTTCGCTTGAGAGTGCGTCGGTTCGGCGGCATTTACGGAGCCACAGCCACAACCC\
                          ACCCTACATCGTAGGTAGTTTAAGGCCAGTCCCTAATGCGTTCGGGGTAGAGTAAGCGAGTCCCT\
                          TCGAGGACCCAAGCTTTTTTCGATGAAACGCGCTTGTATTCTAGTGCTCGCCCGACTACAAGGAG\
                          CCATCGACGTAGGCCGTTAACAAACCTAGATTCTCAGCTGTTTCGTGGAGGACCGCGCAGAAGCT\
                          CCGGATACGCGTTTCGACACGGTAGCCCCCCCGTCTGTGATAGCAGCGAAGAGATTCTTCACAAC\
                          GGTGCGGACTCGAGGGATTCCCTAGTAAGCCTTCGCCCGATCGGGCTACTTACATTCCCTCGCGC\
                          TACTCTCGTAGGGCCAGGTAGGCCAACGCGTTCCGGTACCCGTTTAGTTCTTGTGGGGATCATGG\
                          GAGAGGTATAGTTGCTCGGGCGGGGTGAGCATCGCAGACTCGTTTTTCACTGCGCTCGCGCATCT\
                          GCCACGAGGACATTCGATCATGTGGCGACGTGATCCCTCTTCAGACCTTATCTTGGAGGGCGCAG\
                          CCGTCCGTTCCACCCGAATGTCCGCGGTTTTGGCGACACTGGTAACCTTAGCAGTCAGTACGCGT\
                          AATAGCGACGGGCCCAAGGCTGCGCGTCCACTCGATTGTAGTGCTTCAGGACCTAGCGCTGCTGA\
                          GATAATGGATACAGTAGGCGAAATCGTGATAGTTGCTATGCCGGCCGTAATCAGAACAAACTAAT\
                          GTCGCCAATACTCCACGGCGCACCTATTGACCACGTTTCTTTCCCCATCCCTTTAAATTCCCGCT\
                          GTCCCGGGCATCGGAATAGGAAGGGACTGAGTACTAGAGAGTCCTGCTGGGTC"

    [<Fact>]
    let ``INI : Introduction to the Bioinformatics Armory``() =
        let result = ini rawDna = "185 256 245 212"
        Check.Quick result

module ``Bioinformatics Textbook Track tests`` =

    let data = "TCTTCCACATCTAGCGGAACCTTAGTCTTCCACACCCTTAAGCCCTTAAGCCCTTAAGTCTAGCGGACCTCATGGACCTCATGGTCTAGCGGTC\
                TAGCGGACCTCATGGCCCTTAAGACCTCATGGCCCTTAAGACCTCATGGTCTTCCACATCTTCCACAACCTCATGGTCTAGCGGAACCTTAGTC\
                TAGCGGTCTAGCGGTCTTCCACATCTAGCGGCCCTTAAGCCCTTAAGACCTCATGGAACCTTAGAACCTTAGACCTCATGGTCTTCCACAACCT\
                CATGGTCTTCCACATCTAGCGGTCTAGCGGTCTAGCGGACCTCATGGTCTTCCACATCTTCCACATCTAGCGGACCTCATGGCCCTTAAGACCT\
                CATGGACCTCATGGCCCTTAAGTCTAGCGGTCTTCCACAAACCTTAGTCTAGCGGAACCTTAGTCTTCCACATCTAGCGGTCTTCCACAACCTC\
                ATGGAACCTTAGTCTAGCGGCCCTTAAGACCTCATGGTCTTCCACATCTAGCGGTCTTCCACATCTTCCACACCCTTAAGTCTTCCACATCTAG\
                CGGTCTTCCACAACCTCATGGTCTAGCGGTCTAGCGGAACCTTAGTCTAGCGGACCTCATGGACCTCATGGAACCTTAGACCTCATGGAACCTT\
                AGCCCTTAAGTCTAGCGGTCTAGCGGCCCTTAAGAACCTTAGACCTCATGGTCTTCCACAACCTCATGGTCTAGCGGCCCTTAAGTCTAGCGGT\
                CTTCCACAAACCTTAGCCCTTAAGCCCTTAAGTCTTCCACACCCTTAAGACCTCATGGACCTCATGGAACCTTAGAACCTTAGAACCTTAGTCTAGCGGACCTCATGG"

    [<Fact>]
    let ``1A : Frequent Words Problem``() =
        let result = mostFrequent 13 data = "GTCTTCCACATCT"
        Check.Quick result